server:
  port: ${SERVER_PORT:8001}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/upstream_db?authSource=admin}

