server:
  port: 8083

connectors:
  source-connector:
    connector-class: ${CONNECTOR_CLASS}
    connector-name: ${CONNECTOR_NAME}
    topic-prefix: ${TOPIC_PREFIX}
    database:
      host: ${DB_SOURCE_HOST}
      port: ${DB_SOURCE_PORT}
      user: ${DB_SOURCE_USER}
      password: ${DB_SOURCE_PASSWORD}}


spring:
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: ${ALGOBRAIN_ANALYTICS_DB_DRIVER:org.postgresql.Driver}
    host: ${DBZ_HOST:localhost}
    port: ${DBZ_PORT:5432}
    name: ${DBZ_NAME:postgres}
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}
    username: ${DBZ_USER:postgres}
    password: ${DBZ_PASSWORD:password}

    initialization-mode: always
    continue-on-error: 'true'
    initialize: 'true'
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: 'true'
      ddl-auto: update
